site_name: Amazon EKS RHEL AMI
docs_dir: doc/
site_description: Build template and runtime resources for the Amazon EKS RHEL AMI
repo_name: aws-samples/amazon-eks-ami-rhel
repo_url: https://github.com/aws-samples/amazon-eks-ami-rhel
nav:
  - 'Overview': README.md
  - 'Changelog': CHANGELOG.md
  - 'Community':
    - 'Contribution guidelines': CONTRIBUTING.md
    - 'Code of Conduct': CODE_OF_CONDUCT.md
  - 'Development': development.md
  - 'Usage':
    - 'Overview': usage/overview.md
    - 'Amazon Linux 2023': usage/al2023.md
    - 'Red Hat Enterprise Linux': usage/rhel.md
  - 'nodeadm':
    - 'Overview': nodeadm/README.md
    - 'API':
      - 'Concepts': nodeadm/doc/api-concepts.md
      - 'Reference': nodeadm/doc/api.md
    - 'Examples': nodeadm/doc/examples.md
theme:
  name: material
  palette:
    primary: black
  features:
    - navigation.sections
